<?php

namespace App\Exceptions;

use App\Exceptions\Auth\AdminAuthException;
use App\Exceptions\Auth\UserAuthException;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    /**
     * @param $request
     * @param Throwable $e
     * @return JsonResponse|RedirectResponse|Response|\Symfony\Component\HttpFoundation\Response
     * @throws Throwable
     */
    public function render($request, Throwable $e): Response|JsonResponse|\Symfony\Component\HttpFoundation\Response|RedirectResponse
    {
        if ($e instanceof AdminAuthException) {
            return response()->json([
                'message' => config('exception-messages.admin_auth_failed')
            ], 404);
        }

        if ($e instanceof UserAuthException) {
            return response()->json([
                'message' => config('exception-messages.user_auth_failed')
            ], 404);
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
